# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy dotnet core app to Azure Function App - sethb-testfuncslots2

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '8.0.x' # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DE5C20C919EE40288EA2CC391F9FCF73 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8A966287504B4803B54A5D815D561A2E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7303AE5594174F1FA15555DF03EA62BE }}
      
      - name: Retrieve publish profile for deployment
        id: publishProfileRetrieval
        run: | 
            publishProfiles=$(az webapp deployment list-publishing-profiles \
              --name "<FUNCTION APP NAME>" \
              --resource-group "<RESOURCE GROUP NAME>" \
              --subscription "<SUBSCRIPTION ID>" --xml)
            echo "::add-mask::$publishProfiles"
            echo "::set-output name=publishProfiles::$publishProfiles"
      
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'sethb-testfuncslots2'
          slot-name: 'staging'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ steps.publishProfileRetrieval.outputs.publishProfiles }}
          
